# Copyright © 2025 Seb Garrioch. All rights reserved.
# Published under the MIT License.

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Machine Learning Sample (CI)"
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    name: "Analyze"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Analyze with SonarQube Cloud"
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}